# Generated by Django 4.0.4 on 2022-08-14 11:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('flare', multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Python', 'Python'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('TailwindCSS', 'TailwindCSS'), ('Javascript', 'Javascript')], max_length=45)),
                ('github_link', models.CharField(max_length=350)),
            ],
        ),
    ]
