# Generated by Django 4.0.4 on 2022-08-14 11:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.CharField(max_length=150)),
                ('post', models.TextField(max_length=1500)),
                ('post_time', models.CharField(max_length=2)),
                ('post_url_title', models.CharField(max_length=150)),
                ('flare_choice', multiselectfield.db.fields.MultiSelectField(choices=[('Politics', 'Politics'), ('Tech', 'Tech'), ('Programming', 'Programming'), ('Python', 'Python'), ('Django', 'Django'), ('UI/UX', 'UI/UX'), ('Reviews', 'Reviews'), ('Opinions', 'Opinions'), ('Rant', 'Rant'), ('Uncategorized', 'Uncategorized'), ('Random', 'Random')], max_length=88)),
            ],
        ),
    ]
